import type { Metadata } from "next";
import "./globals.css";
import Providers from "./Provider";
import AuthSideNav from '@/components/AuthSideNav';


export const metadata: Metadata = {
  title: "Convenios ITSVA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, 
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <Providers>

            <AuthSideNav>
              {children}
            </AuthSideNav>

        </Providers>
      </body>
    </html>
  );
}
